export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/snarkjs@0.7.0/build/snarkjs.min.js" async></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
